"""empty message

Revision ID: e3f9e211520b
Revises: 02bc3aa8a949
Create Date: 2025-09-15 12:54:48.740942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3f9e211520b'
down_revision = '02bc3aa8a949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'api_id')
    op.drop_column('ingredients', 'checked_off')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('api_id', sa.Integer(), nullable=True))
    op.add_column('ingredients', sa.Column(
        'checked_off', sa.Boolean(), nullable=False, server_default=sa.text('false')
    ))
    # ### end Alembic commands ###
